#!/usr/bin/env python3
"""Phase 0.5: minimal DAG snapshot safety net for smoke profiles.

This test locks the set of scheduled rule names for each standard test
profile.  Snapshots are stored under test/fixtures/dag_snapshots/ and can
be regenerated with::

    python3 -m pytest test/test_dag_snapshots.py --update-snapshots

The snapshot intentionally excludes:
- timestamps
- absolute paths
- temporary directory names
- Snakemake version strings
- shell commands
- reason lines
"""

import csv
import os
import re
import shutil
import subprocess
import tempfile

import pytest

from conftest import SMOKE_PROFILES
from _tool_resolver import resolve_tool


SNAKEMAKE = resolve_tool("snakemake", "SNAKEMAKE")

# Marker rules that must remain scheduled for specific assay/profile groups.
# These are redundant with the full rule-name snapshot but make regressions
# easier to diagnose.
KEY_MARKERS = {
    "idr": {
        "rules": ["macs3_idr_biorep", "idr_true_replicates"],
        "profiles": ["chipseq_idr_dryrun"],
    },
    "seacr": {
        "rules": ["seacr_bedgraph", "seacr_call"],
        "profiles": ["cuttag_pe_seacr"],
    },
    "cuttag_fragment": {
        "rules": ["cuttag_fragment_size"],
        "profiles": ["cuttag_pe_noctrl", "cuttag_pe_seacr"],
    },
    "mnase": {
        "rules": ["mnase_qc_summary"],
        "profiles": ["mnase_pe_noctrl"],
    },
}


def _discover_placeholders(samples_tsv_path):
    """Return placeholder file paths required for a dry-run."""
    paths = set()
    with open(samples_tsv_path, newline="") as fh:
        reader = csv.DictReader(fh, delimiter="\t")
        for row in reader:
            fq1 = (row.get("fastq_1") or "").strip()
            fq2 = (row.get("fastq_2") or "").strip()
            cb = (row.get("control_bam") or "").strip()
            if fq1:
                paths.add(fq1)
            if fq2:
                paths.add(fq2)
            if cb:
                paths.add(cb)
    return paths


def _rewrite_config(profile_config_path, workdir):
    """Rewrite samples path in profile config to point into workdir."""
    with open(profile_config_path) as fh:
        content = fh.read()
    abs_samples = os.path.join(workdir, "samples.tsv")
    content = re.sub(
        r"^samples:.*$",
        f'samples: "{abs_samples}"',
        content,
        flags=re.MULTILINE,
    )
    return content


def _prepare_workdir(profile_dir, workdir):
    """Create placeholder files and rewritten config in workdir."""
    samples_tsv_src = os.path.join(profile_dir, "samples.tsv")
    config_yaml_src = os.path.join(profile_dir, "config.yaml")

    placeholders = _discover_placeholders(samples_tsv_src)
    for rel_path in placeholders:
        placeholder_path = os.path.join(workdir, os.path.basename(rel_path))
        with open(placeholder_path, "w"):
            pass

    dest_samples = os.path.join(workdir, "samples.tsv")
    shutil.copy2(samples_tsv_src, dest_samples)

    rewritten_config = _rewrite_config(config_yaml_src, workdir)
    dest_config = os.path.join(workdir, "config.yaml")
    with open(dest_config, "w") as fh:
        fh.write(rewritten_config)

    return dest_config


def _extract_rule_names(stdout, stderr):
    """Parse scheduled rule names from snakemake -n output."""
    output = stdout + stderr
    rules = set()
    for line in output.splitlines():
        match = re.match(r"^\s*(?:local)?rule\s+(\w+)\s*:", line)
        if match:
            rules.add(match.group(1))
    return sorted(rules)


def _read_snapshot(snapshot_path):
    """Read rule names from a snapshot file, ignoring comments."""
    with open(snapshot_path) as fh:
        return [
            line.strip()
            for line in fh
            if line.strip() and not line.strip().startswith("#")
        ]


def _write_snapshot(snapshot_path, profile, rules):
    """Write sorted rule names to a snapshot file."""
    os.makedirs(os.path.dirname(snapshot_path), exist_ok=True)
    with open(snapshot_path, "w") as fh:
        fh.write(f"# DAG snapshot for {profile}\n")
        fh.write("# Generated by: snakemake -n\n")
        fh.write("# Format: sorted scheduled rule names, one per line\n")
        fh.write(
            "# Excludes: timestamps, absolute paths, temp dirs, "
            "version strings, shell commands, reasons\n\n"
        )
        for rule in rules:
            fh.write(f"{rule}\n")


def _run_dag_dryrun(profile, profile_dir, snakefile):
    """Run snakemake -n for a profile and return sorted scheduled rule names.

    Creates a temporary workdir with placeholder FASTQ/control_bam files and a
    rewritten config pointing into that workdir.
    """
    workdir = tempfile.mkdtemp(prefix=f"dag_{profile}_", dir="/tmp")
    try:
        dest_config = _prepare_workdir(profile_dir, workdir)
        result = subprocess.run(
            [
                SNAKEMAKE,
                "-s",
                snakefile,
                "--configfile",
                dest_config,
                "-n",
            ],
            cwd=workdir,
            capture_output=True,
            text=True,
            env={**os.environ, "PYTHONDONTWRITEBYTECODE": "1"},
        )

        assert result.returncode == 0, (
            f"snakemake -n failed for {profile}:\n"
            f"stdout:\n{result.stdout}\nstderr:\n{result.stderr}"
        )

        rules = _extract_rule_names(result.stdout, result.stderr)
        assert rules, f"No scheduled rules found for {profile}"
        return rules
    finally:
        shutil.rmtree(workdir, ignore_errors=True)


@pytest.mark.parametrize("profile", SMOKE_PROFILES)
def test_dag_snapshot(profile, snakefile, profiles_dir, snapshots_dir, request):
    """Compare scheduled rule names for a smoke profile to the snapshot."""
    update = request.config.getoption("--update-snapshots")
    profile_dir = os.path.join(profiles_dir, profile)
    snapshot_path = os.path.join(snapshots_dir, f"{profile}.txt")

    rules = _run_dag_dryrun(profile, profile_dir, snakefile)

    if update:
        _write_snapshot(snapshot_path, profile, rules)
        pytest.skip(f"Updated snapshot for {profile}")

    assert os.path.exists(snapshot_path), (
        f"Snapshot missing for {profile}; run with --update-snapshots"
    )

    expected = _read_snapshot(snapshot_path)
    assert rules == expected, (
        f"DAG snapshot mismatch for {profile}:\n"
        f"missing in current: {set(expected) - set(rules)}\n"
        f"extra in current: {set(rules) - set(expected)}"
    )


@pytest.mark.parametrize("profile", SMOKE_PROFILES)
def test_key_markers(profile, snapshots_dir, request):
    """Assert that assay-specific key rules remain scheduled where expected."""
    update = request.config.getoption("--update-snapshots")
    if update:
        pytest.skip("Key marker check not needed during snapshot update")

    snapshot_path = os.path.join(snapshots_dir, f"{profile}.txt")
    if not os.path.exists(snapshot_path):
        pytest.skip(f"Snapshot missing for {profile}")

    rules = set(_read_snapshot(snapshot_path))
    for marker_name, marker in KEY_MARKERS.items():
        if profile in marker["profiles"]:
            for rule in marker["rules"]:
                assert rule in rules, (
                    f"{profile}: expected {marker_name} marker rule {rule!r} "
                    f"not found in snapshot"
                )
